# Generated by Django 2.1.5 on 2019-01-25 20:27

from django.db import migrations, models
import sandbox.foo.snippets
import wagtail.core.fields
import wagtailcloudinary.blocks
import wagtailcloudinary.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', wagtailcloudinary.fields.CloudinaryField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='foopage',
            name='body',
            field=wagtail.core.fields.StreamField([('image', wagtailcloudinary.blocks.CloudinaryImageBlock()), ('snippet_image', wagtailcloudinary.blocks.CloudinarySnippetChooserBlock(sandbox.foo.snippets.ImageSnippet))], blank=True),
        ),
    ]
