# Generated by Django 3.2.11 on 2023-02-01 23:44

from django.db import migrations
import wagtail.fields

import sandbox.foo.snippets
import wagtailcloudinary.blocks
import wagtailcloudinary.fields


class Migration(migrations.Migration):
    dependencies = [
        ("foo", "0002_auto_20190125_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foopage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "image",
                        wagtailcloudinary.blocks.CloudinaryImageBlock(required=False),
                    ),
                    (
                        "snippet_image",
                        wagtailcloudinary.blocks.CloudinarySnippetChooserBlock(
                            sandbox.foo.snippets.ImageSnippet
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="foopage",
            name="image",
            field=wagtailcloudinary.fields.CloudinaryField(blank=True, max_length=255),
        ),
    ]
