test:
  image: python:3.7
  services:
    - name: postgres
      alias: db
  script:
    - echo "checking to see if this is exactly how this works..."
    - pip install -r requirements.txt
    - ./manage.py test


variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
