repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.4.1"
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, scss, yaml, json]

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        types: [file, python]
