[tox]
isolated_build = True
envlist =
    py{311,312,313,314}-django{520}-wagtail{70,74}

[testenv]
runner = uv-venv-runner
allowlist_externals =
    bash
    ruff
deps =
    django520: django>=5.2,<5.3
    wagtail70: wagtail>=7.0,<7.1
    wagtail74: wagtail>=7.4,<7.5
setenv =
    PYTHONWARNINGS = d
commands =
    ruff check {toxinidir}/wagtailcloudinary {toxinidir}/sandbox
